tasks:
- s3tests:
    client.0:
      sts_tests: True
      extra_attrs: ["test_of_sts"]
      force-branch: wip-rgw-sts-session-policy-fixes
      git_remote: https://github.com/pritha-srivastava/
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
              rgw sts key: abcdefghijklmnop
              rgw s3 auth use sts: true
